"""
Classifier module - Sends compliance findings to the Claude API for AI-powered analysis.
"""

import logging
import os
import json
import time
from typing import Any
from opentelemetry import trace, metrics

import anthropic
# NOTE: removed the observability import here - classifier doesn't initialize it,
# main.py does. classifier just USES the already-configured tracer and meter.

logger = logging.getLogger(__name__)

tracer = trace.get_tracer(__name__)
meter = metrics.get_meter(__name__)

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
MODEL = "claude-haiku-4-5-20251001"

# ===========================================================================
# CHANGED: Metric instruments are created ONCE here at module level, NOT
# inside classify_finding. Creating them inside the function would rebuild
# them on every single call (11 times in your run), which is wasteful and
# wrong. Instruments are long-lived objects: create once, use many times.
# ===========================================================================

# Pricing constants for Claude Haiku (per million tokens). Verify current rates.
INPUT_COST_PER_MTOK = 0.80
OUTPUT_COST_PER_MTOK = 4.00

input_tokens_counter = meter.create_counter(
    name="llm.tokens.input",
    description="Total input tokens sent to Claude",
    unit="1",
)
output_tokens_counter = meter.create_counter(
    name="llm.tokens.output",
    description="Total output tokens generated by Claude",
    unit="1",
)
llm_latency = meter.create_histogram(
    name="llm.call.duration",
    description="Duration of each Claude API call",
    unit="s",
)
llm_cost_counter = meter.create_counter(
    name="llm.cost.usd",
    description="Estimated cost of Claude API calls in USD",
    unit="1",
)


def build_classification_prompt(finding: dict[str, Any]) -> str:
    """Build a structured prompt for Claude to analyze a single finding."""
    return f"""You are a senior security engineer and PCI-DSS compliance expert.
Analyze this compliance finding and respond with ONLY a valid JSON object, no other text.

Finding details:
- Container: {finding['container']}
- Rule violated: {finding['rule_id']}
- Description: {finding['description']}
- Severity: {finding['severity']}
- PCI-DSS Control: {finding['pci_control']}
- Declared (expected): {finding['declared']}
- Observed (actual): {finding['observed']}

Respond with exactly this JSON structure:
{{
    "attack_scenario": "A specific 2-3 sentence description of how an attacker could exploit this misconfiguration",
    "business_risk": "A specific 1-2 sentence explanation of the business and compliance risk",
    "remediation_steps": ["step 1", "step 2", "step 3"],
    "pci_requirement_detail": "One sentence explaining exactly which part of {finding['pci_control']} this violates",
    "estimated_fix_time": "e.g. 15 minutes, 1 hour, 1 day"
}}"""


def classify_finding(
    client: anthropic.Anthropic,
    finding: dict[str, Any]
) -> dict[str, Any]:
    """Send a single finding to the Claude API and return the enriched analysis."""
    logger.info(f"Classifying finding: {finding['rule_id']} on {finding['container']}")

    try:
        prompt = build_classification_prompt(finding)

        # CHANGED: everything that belongs to this operation is now correctly
        # indented INSIDE the 'with' block. This was the indentation error.
        # CHANGED: marked the span kind as CLIENT because this is an outbound
        # API call (crossing a network boundary to Anthropic), not internal work.
        with tracer.start_as_current_span(
            "llm.classify_finding",
            kind=trace.SpanKind.CLIENT,
        ) as span:
            # Add context about WHICH finding this span is classifying
            span.set_attribute("llm.model", MODEL)
            span.set_attribute("finding.rule_id", finding["rule_id"])
            span.set_attribute("finding.container", finding["container"])

            start = time.time()  # mark when the API call begins

            response = client.messages.create(
                model=MODEL,
                max_tokens=1024,
                messages=[{"role": "user", "content": prompt}],
            )

            # CHANGED: compute duration AFTER the call returns
            duration = time.time() - start

            # NEW: read token usage from the response. The Anthropic SDK
            # returns a .usage object with input_tokens and output_tokens.
            input_tokens = response.usage.input_tokens
            output_tokens = response.usage.output_tokens

            # NEW: compute estimated cost from the token counts
            cost = (
                (input_tokens / 1_000_000) * INPUT_COST_PER_MTOK
                + (output_tokens / 1_000_000) * OUTPUT_COST_PER_MTOK
            )

            # --- Attach everything to the SPAN (for the trace view) ---
            span.set_attribute("llm.input_tokens", input_tokens)
            span.set_attribute("llm.output_tokens", output_tokens)
            span.set_attribute("llm.latency_ms", round(duration * 1000, 2))
            span.set_attribute("llm.cost_usd", round(cost, 6))

            # --- Record METRICS (for dashboards and aggregation) ---
            # CHANGED: now uses the real variables (input_tokens, duration, etc.)
            # instead of undefined names. The 'model' attribute lets you break
            # the metric down by model in Grafana.
            model_attrs = {"model": MODEL}
            input_tokens_counter.add(input_tokens, attributes=model_attrs)
            output_tokens_counter.add(output_tokens, attributes=model_attrs)
            llm_latency.record(duration, attributes=model_attrs)
            llm_cost_counter.add(cost, attributes=model_attrs)

            # Parse the response (this stays inside the span so any
            # parsing time is captured within the span's duration)
            raw_response = response.content[0].text
            cleaned = raw_response.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[-1]
                cleaned = cleaned.rsplit("```", 1)[0]
                cleaned = cleaned.strip()

            ai_analysis = json.loads(cleaned)

            enriched = {
                **finding,
                "attack_scenario": ai_analysis.get("attack_scenario", "N/A"),
                "business_risk": ai_analysis.get("business_risk", "N/A"),
                "remediation_steps": ai_analysis.get("remediation_steps", []),
                "pci_requirement_detail": ai_analysis.get("pci_requirement_detail", "N/A"),
                "estimated_fix_time": ai_analysis.get("estimated_fix_time", "N/A"),
                "ai_classified": True,
            }

            logger.info(f"Successfully classified: {finding['rule_id']} on {finding['container']}")
            return enriched

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Claude response as JSON: {e}")
        return {
            **finding,
            "ai_classified": False,
            "classification_error": str(e),
        }

    except Exception as e:
        logger.error(f"Classification error for {finding['rule_id']}: {e}")
        return {
            **finding,
            "ai_classified": False,
            "classification_error": str(e),
        }
def classify_all(evaluation_result: dict[str, Any]) -> dict[str, Any]:
    """
    Run AI classification on all findings from the evaluator.
    evaluation_result: the full output from evaluator.evaluate_all()
    Returns the evaluation result with all findings enriched by Claude AI analysis.
    This is the main entry point called by main.py.
    """
    if not ANTHROPIC_API_KEY:
        raise ValueError(
            "ANTHROPIC_API_KEY environment variable is not set. "
            "Copy .env.example to .env and add your API key."
        )

    client = anthropic.Anthropic()

    findings = evaluation_result.get("findings", [])
    logger.info(f"Starting AI classification of {len(findings)} findings...")

    classified_findings = []
    for i, finding in enumerate(findings):
        logger.info(f"Classifying finding {i+1} of {len(findings)}...")
        classified = classify_finding(client, finding)
        classified_findings.append(classified)

    successful = sum(1 for f in classified_findings if f.get("ai_classified"))

    logger.info(
        f"Classification complete: {successful}/{len(findings)} "
        f"findings successfully classified by AI"
    )

    return {
        "findings": classified_findings,
        "summary": {
            **evaluation_result["summary"],
            "ai_classified": successful,
        }
    }